spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

urls:
  AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
  USER_SERVICE_URL: ${USER_SERVICE_URL}

server:
  port: 8080