apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-db-secret
  namespace: anadea
  labels:
    app: user-postgres-db
type: Opaque
stringData:
  POSTGRES_DB: user_postgres_db
  POSTGRES_USER: user_postgres_db_user
  POSTGRES_PASSWORD: pass
  DB_HOST: user-postgres-db
  DB_PORT: "5432"