apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: anadea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: anadea-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_BASE_URL
              value: "http://anadea.ua"