apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-postgres-db-volume
  namespace: anadea
  labels:
    type: local
    app: auth-postgres-db
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/auth_postgres_db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-db-volume-claim
  namespace: anadea
  labels:
    app: auth-postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi