apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres-db-secret
  namespace: anadea
  labels:
    app: auth-postgres-db
type: Opaque
stringData:
  POSTGRES_DB: auth_postgres_db
  POSTGRES_USER: auth_postgres_db_user
  POSTGRES_PASSWORD: pass
  DB_HOST: auth-postgres-db
  DB_PORT: "5432"